config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :users do
    resources :decks
    resources :formats
  end
  scope :decks do
    resources :cards
  end

  post '/decks/cards/new', to: 'cards#new'

  root 'welcome#home'

  get '/login', to: 'sessions#new', as: 'login'
  post '/session', to: 'sessions#create', as: 'session'
  delete '/session/', to: 'sessions#destroy', as: 'logout'



  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/format.rb
class Format < ApplicationRecord
    has_many :decks
end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
    def show
      @formats = Format.all
      @format = Format.find(params[:id])
      @user = current_user
      @decks = @user.decks.filter_by_format(params[:id])
    end
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/views/formats/_form_html.erb
<h3 class="text-center">Here are your <%="#{@format.name}"%> decks.</h3>

<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Deck Name</th>
      <th scope="col">Format</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @decks.each do |deck| %>
    <tr class="table-light">
      <th scope="row"><%= link_to "#{deck.name}", user_deck_path(@user, deck)%></th>
      <td> <%= link_to "#{deck.format.name}", user_format_path(@user, deck.format) %></td>
      <td> <%= link_to("", user_deck_path(@user, deck), method: :delete, class: "btn btn-danger") %> </td>

    <% end %>
  </tr>
  </tbody>
</table>