config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :users do
    resources :decks
    resources :formats
  end
  scope :decks do
    resources :cards
  end

  post '/decks/cards/new', to: 'cards#new'

  root 'welcome#home'

  get '/login', to: 'sessions#new', as: 'login'
  post '/session', to: 'sessions#create', as: 'session'
  delete '/session/', to: 'sessions#destroy', as: 'logout'



  get '/auth/facebook/callback' => 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<%= content_tag(:div, flash[:error], :class => "errors") if flash[:error] %>
<%= content_tag(:div, flash[:notice], :class => "errors") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], :class => "errors") if flash[:alert] %>

app/views/layouts/_navigation_links.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<a class="navbar-brand" href="/">DeckStorage</a>
<% if !current_user %>
| <%= link_to "Sign Up", new_user_path %>
| <%= link_to "Log In", login_path %>
| <%= link_to "Facebook Log In", '/auth/facebook' %> |
<% end %>
<% if current_user %>
| <%= link_to "#{current_user.name}'s profile", user_path(current_user) %>
| <%= link_to "Log Out", logout_path, method:'delete' %> |
<% end %>
</nav>

app/views/layouts/_profile_links.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">DeckStorage</a>
  <% if current_user %>
  | <%= link_to "#{current_user.name}'s profile", user_path(current_user) %>
  | <%= link_to "Log Out", logout_path, method:'delete' %> |
  <% end %>
  <% if !current_user %>
  | <%= link_to 'Sign up', new_user_path %>
  | <%= link_to 'Log in', login_path %>
  | <%= link_to "Facebook Log In", '/auth/facebook' %> |
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deckbox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <%= render partial: "layouts/navigation_links" %>
      </div>

      <div class="content">
        <%= render partial: "layouts/errors" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>